
[package]
name = "game_dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
fyrox_sokoban = { path = "../game", default-features = false }

[features]
default = ["fyrox_sokoban/default"]
dylib-engine = ["fyrox_sokoban/dylib-engine"]
