
[package]
name = "fyrox_sokoban"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = {workspace = true}
sokoban = {path= "../../", default-features = false, features = ["fyrox"]}

[features]
default = ["fyrox/default"]
dylib-engine = ["fyrox/dylib"]
