
[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = { workspace = true }
fyrox_sokoban = { path = "../game", optional = true }

[features]
default = ["fyrox_sokoban"]
dylib = ["fyrox/dylib"]
